#!/usr/bin/env node
// Generates docs/ASSETS.md from public/assets/manifest.json + parts (PLAN.md §6).
//
//   node tools/assets-doc.mjs [--check]
//
// Output is deterministic (no timestamps) so the doc only changes when the manifest or the files do.
// --check exits 1 if docs/ASSETS.md is out of date instead of writing it.
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { ROOT, ensureDir, parseArgs } from "./lib/common.mjs";
import { FORMATS, inspectEntry, loadManifestParts, triBudget } from "./lib/manifest.mjs";

const a = parseArgs(process.argv.slice(2), ["check"]);
const { entries, parts, errors } = loadManifestParts();
if (errors.length) {
  console.error(`manifest has errors (run npm run assets:check):\n  ${errors.join("\n  ")}`);
  process.exit(1);
}

const cell = (s) => String(s ?? "").replace(/\|/g, "\\|").replace(/\n/g, " ");
const code = (s) => (s ? `\`${s}\`` : "");

const TYPE_GUIDE = {
  gltf: "Binary glTF 2.0 (`.glb`, preferred) or `.gltf` with embedded buffers. Metres, Y up. Apply transforms before export. Keep to one material where the spec says so.",
  texture: "PNG/JPG/WebP (or KTX2). Power-of-two sizes. Seamless where the spec says tileable. sRGB colour unless `srgb: false`.",
  sprite: "SVG (preferred) or PNG/WebP with transparency, used by the DOM UI as an `<img>`.",
  audio: "OGG (preferred) or MP3, mono, 44.1 kHz, trimmed with no leading silence.",
  font: "WOFF2.",
  json: "UTF-8 JSON.",
};

const lines = [];
lines.push("# Assets");
lines.push("");
lines.push("<!-- GENERATED by tools/assets-doc.mjs from public/assets/manifest.json. Do not edit by hand: run `npm run assets:doc`. -->");
lines.push("");
lines.push("Every visual, audio and UI asset is referenced **only** by manifest id. Game code never contains file paths, so art can be swapped with zero code changes.");
lines.push("");
lines.push("## How to swap an asset");
lines.push("");
lines.push("1. Find the asset below and read its brief (size, pivot, orientation, budget, clip names).");
lines.push("2. Put your file at the listed path under `public/assets/` (or edit that entry's `src` in the part file to point at your file).");
lines.push("3. Run `npm run assets:check`. It validates the format, image size, glTF triangle budget and animation clip names, and lists the ids that still use placeholders.");
lines.push("4. Run `npm run assets:doc` to refresh this page, then `npm run dev` and look at it in the game.");
lines.push("");
lines.push("A missing or broken file never breaks the game. The engine falls back to the entry's procedural `placeholder` and logs one console warning.");
lines.push("");
lines.push("### Conventions");
lines.push("");
lines.push("- Units are metres. 1 world unit = 1 m. The runner is about 1.7 m tall and lanes are about 2.5 m apart.");
lines.push("- Models face **-Z** (the run direction) unless the entry's `forward` says otherwise. `pivot` names where the origin must be: `feet-center`, `bottom-center` or `center`.");
lines.push("- `animations` maps the engine's logical names to the clip names that must exist inside the glTF. Names are case-sensitive.");
lines.push("- The manifest is split into parts so parallel work does not collide: " + parts.map((p) => code(`public/assets/${p.name}`)).join(", ") + ". Ids must be unique across parts.");
lines.push("");
lines.push("### Formats by type");
lines.push("");
lines.push("| type | extensions | guidance |");
lines.push("|---|---|---|");
for (const [t, exts] of Object.entries(FORMATS)) lines.push(`| ${t} | ${exts.join(" ")} | ${TYPE_GUIDE[t]} |`);
lines.push("");

const present = entries.filter((e) => inspectEntry(e).exists).length;
lines.push("## Status");
lines.push("");
lines.push(`${entries.length} assets in ${parts.length} parts. ${present} have files and ${entries.length - present} still use procedural placeholders.`);
lines.push("");

for (const part of parts) {
  const list = entries.filter((e) => e.part === part.name);
  lines.push(`## ${part.part} (${code(`public/assets/${part.name}`)})`);
  lines.push("");
  if (part.description) lines.push(part.description, "");
  lines.push("| id | type | file (under public/assets/) | status | pivot / facing | budget |");
  lines.push("|---|---|---|---|---|---|");
  for (const e of list) {
    const info = inspectEntry(e);
    let status = info.exists ? "file" : `placeholder (${code(e.placeholder)})`;
    if (info.exists && info.dims) status += ` ${info.dims.width}x${info.dims.height}`;
    if (info.exists && info.gltf) status += `, ${info.gltf.tris} tris`;
    const pivot = [e.pivot, e.forward ? `faces ${e.forward}` : ""].filter(Boolean).join(", ");
    const tris = triBudget(e.spec);
    lines.push(`| ${code(e.id)} | ${e.type} | ${code(e.src)} | ${cell(status)} | ${cell(pivot)} | ${tris ? `<= ${tris} tris` : ""} |`);
  }
  lines.push("");
  for (const e of list) {
    lines.push(`### ${code(e.id)}`);
    lines.push("");
    lines.push(`- **File:** ${code(`public/assets/${e.src}`)} (${e.type}: ${FORMATS[e.type].join(", ")})`);
    if (e.pivot || e.forward) lines.push(`- **Pivot / facing:** ${[e.pivot, e.forward && `faces ${e.forward}`].filter(Boolean).join(", ")}`);
    if (e.scale !== undefined) lines.push(`- **Scale applied by engine:** ${e.scale}`);
    if (e.animations) lines.push(`- **Animation clips required:** ${Object.entries(e.animations).map(([k, v]) => `${k} → ${code(v)}`).join(", ")}`);
    if (e.maps) lines.push(`- **Uses textures:** ${Object.entries(e.maps).map(([k, v]) => `${k} = ${code(v)}`).join(", ")}`);
    if (e.repeat) lines.push(`- **Tiling:** repeat ${e.repeat.join(" x ")}`);
    if (e.srgb !== undefined) lines.push(`- **Colour space:** ${e.srgb ? "sRGB" : "linear (data)"}`);
    if (e.volume !== undefined) lines.push(`- **Playback volume:** ${e.volume}${e.loop ? ", looped" : ""}`);
    if (e.color) lines.push(`- **Placeholder tint / palette hint:** ${code(e.color)}`);
    lines.push(`- **Placeholder:** ${code(e.placeholder)}`);
    if (e.spec) lines.push(`- **Brief:** ${e.spec}`);
    lines.push("");
  }
}

const out = lines.join("\n").replace(/\n{3,}/g, "\n\n");
const target = join(ROOT, "docs", "ASSETS.md");
if (a.check) {
  const current = existsSync(target) ? readFileSync(target, "utf8").replace(/\r\n/g, "\n") : "";
  if (current !== out) {
    console.error("docs/ASSETS.md is out of date: run npm run assets:doc");
    process.exit(1);
  }
  console.log("docs/ASSETS.md is up to date");
} else {
  ensureDir(join(ROOT, "docs"));
  writeFileSync(target, out);
  console.log(`wrote docs/ASSETS.md (${entries.length} assets, ${parts.length} parts)`);
}
