#!/usr/bin/env node
// Generates docs/TUNING.md from the LIVE tuning registry (plus the cheat and scenario registries).
// The registry is populated at runtime by each system's defineTuning() call, so this tool opens the
// built game in Chrome (?debug=1) and reads window.__game.tuningSchema() / cheats() / scenarios().
//
//   node tools/tuning-doc.mjs [--port 5100] [--check]
//
// Deterministic output (no timestamps). --check exits 1 when docs/TUNING.md is out of date.
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { launchChrome, waitForGame } from "./lib/browser.mjs";
import { ROOT, ensureDir, num, parseArgs } from "./lib/common.mjs";
import { ensureBuild, ensurePreview } from "./lib/server.mjs";

const a = parseArgs(process.argv.slice(2), ["check"]);
const port = num(a.port, 5100);
const cell = (s) => String(s ?? "").replace(/\|/g, "\\|").replace(/\n/g, " ");

ensureBuild();
const server = await ensurePreview({ port });
const browser = await launchChrome();
let data;
try {
  const page = await browser.newPage({ viewport: { width: 540, height: 960 } });
  await page.goto(`${server.url}?debug=1&clock=manual&mute=1`);
  await waitForGame(page);
  data = await page.evaluate(() => ({
    tuning: window.__game.tuningSchema(),
    cheats: window.__game.cheats(),
    scenarios: window.__game.scenarios(),
  }));
} finally {
  await browser.close();
  await server.stop();
}

const L = [];
L.push("# Tuning");
L.push("");
L.push("<!-- GENERATED by tools/tuning-doc.mjs from the live tuning registry. Do not edit by hand: run `npm run docs:tuning`. -->");
L.push("");
L.push("Every gameplay number lives in the tuning registry (`src/core/tuning.ts`), registered by the system that owns it. Nothing reads a magic constant.");
L.push("");
L.push("## How it works");
L.push("");
L.push("```ts");
L.push('import { defineTuning } from "../../core/tuning";');
L.push('export const PLAYER = defineTuning("player", "Player", {');
L.push('  jumpHeight: { default: 1.35, min: 0.5, max: 3, step: 0.05, label: "Jump apex height", unit: "m" },');
L.push("});");
L.push("PLAYER.jumpHeight; // live number, updated in place (zero-allocation reads in the hot loop)");
L.push("```");
L.push("");
L.push("- Paths are `<group>.<key>`, for example `player.jumpHeight`. Values are clamped to `[min, max]`.");
L.push("- Change a value live, mid-run, without a restart: `window.__game.setTuning(\"player.jumpHeight\", 1.6)`. Read all values with `window.__game.getTuning()` and the schema with `window.__game.tuningSchema()`.");
L.push("- Setting a path before its group registers keeps the value pending and applies it on registration, so presets can load early.");
L.push("- The in-game editor (piece D2) builds itself from this registry. Adding an entry needs zero editor code.");
L.push("- After adding or changing entries run `npm run docs:tuning` to refresh this page.");
L.push("");

const groups = new Map();
for (const e of data.tuning) {
  if (!groups.has(e.group)) groups.set(e.group, { label: e.groupLabel, items: [] });
  groups.get(e.group).items.push(e);
}
L.push(`## Registry (${data.tuning.length} fields in ${groups.size} groups)`);
L.push("");
L.push(groups.size ? [...groups].map(([g, v]) => `[${v.label}](#${g})`).join(" · ") : "_empty_");
L.push("");
for (const [g, v] of groups) {
  L.push(`<a id="${g}"></a>`);
  L.push(`### ${v.label} (\`${g}\`)`);
  L.push("");
  L.push("| path | label | default | min | max | step | unit |");
  L.push("|---|---|---|---|---|---|---|");
  for (const e of v.items) L.push(`| \`${e.path}\` | ${cell(e.label)}${e.help ? `. ${cell(e.help)}` : ""} | ${e.default} | ${e.min} | ${e.max} | ${e.step} | ${cell(e.unit ?? "")} |`);
  L.push("");
}

L.push(`## Cheats (${data.cheats.length})`);
L.push("");
L.push("Callable as `window.__game.cheat(name, ...args)` and from the dev panel (see DEVTOOLS.md).");
L.push("");
L.push("| name | label | group |");
L.push("|---|---|---|");
for (const c of data.cheats) L.push(`| \`${c.name}\` | ${cell(c.label)} | ${cell(c.group)} |`);
L.push("");
L.push(`## Game scenarios (${data.scenarios.length})`);
L.push("");
L.push("Deterministic layouts for `window.__game.startRun({ scenario })`, captures and tests (`src/game/spawn/scenarios.ts`).");
L.push("");
L.push("| id | description |");
L.push("|---|---|");
for (const s of data.scenarios) L.push(`| \`${s.id}\` | ${cell(s.description)} |`);
L.push("");

const out = L.join("\n");
const target = join(ROOT, "docs", "TUNING.md");
if (a.check) {
  const cur = existsSync(target) ? readFileSync(target, "utf8").replace(/\r\n/g, "\n") : "";
  if (cur !== out) {
    console.error("docs/TUNING.md is out of date: run npm run docs:tuning");
    process.exit(1);
  }
  console.log("docs/TUNING.md is up to date");
} else {
  ensureDir(join(ROOT, "docs"));
  writeFileSync(target, out);
  console.log(`wrote docs/TUNING.md (${data.tuning.length} fields, ${groups.size} groups, ${data.cheats.length} cheats, ${data.scenarios.length} scenarios)`);
}
